### ISSUE TITLE
系统指纹库发生改变后怎么进行下一次验证

### ISSUE THREAD

**Issue by AndyFrist** [Likeyong/FingerManagerCompat#1]
系统指纹库增加指纹后，一直提示“指纹数据发生了变化”怎么进行下次一次验证呢？

**Comment by Likeyong** [comment]
> 系统指纹库增加指纹后，一直提示“指纹数据发生了变化”怎么进行下次一次验证呢？


@天狮666888 调用FingerManager的updateFingerData（） 最新版本是1.0.1

**Comment by AndyFrist** [comment]
Android8.1机型上，BiometricPromptImpl23类中113行代码byte[] bytes = cipher.doFinal();

总是报javax.crypto.AEADBadTagException。这句代码有什么用，可以删除吗？

**Comment by Likeyong** [comment]
> Android8.1机型上，BiometricPromptImpl23类中113行代码byte[] bytes = cipher.doFinal();
> 
> 总是报javax.crypto.AEADBadTagException。这句代码有什么用，可以删除吗？

是指纹数据发生变化的情况下吗

**Comment by AndyFrist** [comment]
不是，卸载重新运行起来也是报这个异常呢

**Comment by Likeyong** [comment]
> 不是，卸载重新运行起来也是报这个异常呢



> Android8.1机型上，BiometricPromptImpl23类中113行代码byte[] bytes = cipher.doFinal();
> 
> 总是报javax.crypto.AEADBadTagException。这句代码有什么用，可以删除吗？



> Android8.1机型上，BiometricPromptImpl23类中113行代码byte[] bytes = cipher.doFinal();
> 
> 总是报javax.crypto.AEADBadTagException。这句代码有什么用，可以删除吗？

这个不能删除,我无法复现你的问题,,回头我找8.1 的设备试试

**Comment by Likeyong** [comment]
> Android8.1机型上，BiometricPromptImpl23类中113行代码byte[] bytes = cipher.doFinal();
> 
> 总是报javax.crypto.AEADBadTagException。这句代码有什么用，可以删除吗？

你依赖的时什么版本

**Comment by xyh976039745** [comment]
这个问题还是存在啊，你们怎么解决的

**Comment by Likeyong** [comment]
> 这个问题还是存在啊，你们怎么解决的

想问一下用的是什么版本

**Comment by AndyFrist** [comment]
没解决，产品妥协了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月15日(周一) 上午10:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Likeyong/FingerManagerCompat] 系统指纹库发生改变后怎么进行下一次验证 (#1)




  
这个问题还是存在啊，你们怎么解决的
  
想问一下用的是什么版本

**Comment by Likeyong** [comment]
> 没解决，产品妥协了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年3月15日(周一) 上午10:05 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Likeyong/FingerManagerCompat] 系统指纹库发生改变后怎么进行下一次验证 (#1) 这个问题还是存在啊，你们怎么解决的 想问一下用的是什么版本 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好吧,能告诉一下,你在什么机型出现的这个问题吗? 系统版本号是多少, 依赖这个库的版本是1.0.2 吗? 我想查一下原因

**Comment by UserName-Haha** [comment]
我这边也遇到同样的问题了，一直提示指纹变化，无法进行正常的指纹验证。设备：锤子，系统版本：Android7.1.2

**Comment by UserName-Haha** [comment]
> > 不是，卸载重新运行起来也是报这个异常呢
> 
> > Android8.1机型上，BiometricPromptImpl23类中113行代码byte[] bytes = cipher.doFinal();
> > 总是报javax.crypto.AEADBadTagException。这句代码有什么用，可以删除吗？
> 
> > Android8.1机型上，BiometricPromptImpl23类中113行代码byte[] bytes = cipher.doFinal();
> > 总是报javax.crypto.AEADBadTagException。这句代码有什么用，可以删除吗？
> 
> 这个不能删除,我无法复现你的问题,,回头我找8.1 的设备试试

为什么不能删，这一行代码我看仅仅只是调用了一下，好像没啥具体的作用。有什么特殊的考虑吗？

**Comment by Likeyong** [comment]
> > > 不是，卸载重新运行起来也是报这个异常呢
> > 
> > 
> > > Android8.1机型上，BiometricPromptImpl23类中113行代码byte[] bytes = cipher.doFinal();
> > > 总是报javax.crypto.AEADBadTagException。这句代码有什么用，可以删除吗？
> > 
> > 
> > > Android8.1机型上，BiometricPromptImpl23类中113行代码byte[] bytes = cipher.doFinal();
> > > 总是报javax.crypto.AEADBadTagException。这句代码有什么用，可以删除吗？
> > 
> > 
> > 这个不能删除,我无法复现你的问题,,回头我找8.1 的设备试试
> 
> 为什么不能删，这一行代码我看仅仅只是调用了一下，好像没啥具体的作用。有什么特殊的考虑吗？

这行报错原因是因为系统认证失败了,你用的库版本是哪个版本?

**Comment by Likeyong** [comment]
> 我这边也遇到同样的问题了，一直提示指纹变化，无法进行正常的指纹验证。设备：锤子，系统版本：Android7.1.2

最新的版本是1.0.2,你可能需要把项目拉下来才能跑,收到"指纹发生变化"回调的时候调用FingerManager.updateFingerData(MainActivity.this);

**Comment by UserName-Haha** [comment]
是最新版，目前遇到另一个错误，我这边开启指纹后，在系统设置里将指纹全部删除，此时再次在App内唤起指纹就会报错。错误信息：
 Caused by: java.security.InvalidKeyException: Only SecretKey is supported
                                                                                                    	at com.android.org.conscrypt.OpenSSLCipher.checkAndSetEncodedKey(OpenSSLCipher.java:435)
                                                                                                    	at com.android.org.conscrypt.OpenSSLCipher.engineInit(OpenSSLCipher.java:260)
                                                                                                    	at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2977)
                                                                                                    	at javax.crypto.Cipher.tryCombinations(Cipher.java:2884)
                                                                                                    	at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2789)
                                                                                                    	at javax.crypto.Cipher.chooseProvider(Cipher.java:956)
                                                                                                    	at javax.crypto.Cipher.init(Cipher.java:1199)
                                                                                                    	at javax.crypto.Cipher.init(Cipher.java:1143)

感觉应该是 CipherHelper.initCipher 里的逻辑有问题

**Comment by Likeyong** [comment]
> 是最新版，目前遇到另一个错误，我这边开启指纹后，在系统设置里将指纹全部删除，此时再次在App内唤起指纹就会报错。错误信息： Caused by: java.security.InvalidKeyException: Only SecretKey is supported at com.android.org.conscrypt.OpenSSLCipher.checkAndSetEncodedKey(OpenSSLCipher.java:435) at com.android.org.conscrypt.OpenSSLCipher.engineInit(OpenSSLCipher.java:260) at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2977) at javax.crypto.Cipher.tryCombinations(Cipher.java:2884) at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2789) at javax.crypto.Cipher.chooseProvider(Cipher.java:956) at javax.crypto.Cipher.init(Cipher.java:1199) at javax.crypto.Cipher.init(Cipher.java:1143)
> 
> 感觉应该是 CipherHelper.initCipher 里的逻辑有问题

指纹识别正规流程应该是,先检查是被是否支持指纹识别,然后再检查系统中是否有指纹数据,如果系统没有指纹数据,就应该提示先去系统设置中录入指纹数据.通过FingerManager .checkSupport()检查是否支持指纹和是否有指纹数据
