### ISSUE TITLE
每次都是弹出错误对话框，请重试，换个手指试试

### ISSUE THREAD

**Issue by AndyFrist** [Likeyong/FingerManagerCompat#3]
初始化的过程就进行了一次识别操作吗？我看demo也是一样的呢，怎么处理

**Comment by Likeyong** [comment]
没明白你的意思, 能贴上代码 吗

**Comment by Likeyong** [comment]
> 初始化的过程就进行了一次识别操作吗？我看demo也是一样的呢，怎么处理

你换个设备试试呢,我在用小米5s的时候,因为指纹硬件垃圾,我手指没放上去,系统就识别到我放上去了

**Comment by AndyFrist** [comment]
应该不是硬件问题，我手里好几个手机都是这样子的



---原始邮件---
发件人: "Likeyong"<notifications@github.com&gt;
发送时间: 2020年5月12日(周二) 下午4:21
收件人: "Likeyong/FingerManagerCompat"<FingerManagerCompat@noreply.github.com&gt;;
抄送: "AndyFrist"<1609798079@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Likeyong/FingerManagerCompat] 每次都是弹出错误对话框，请重试，换个手指试试 (#3)




  
初始化的过程就进行了一次识别操作吗？我看demo也是一样的呢，怎么处理
  
你换个设备试试呢,我在用小米5s的时候,因为指纹硬件垃圾,我手指没放上去,系统就识别到我放上去了

**Comment by AndyFrist** [comment]
把您的GitHub上的的代码拉下来运行的例子，在Android8.1上每次都是弹出"请重试，换个手指试试"。看代码好像defaultDialog中onHelp会执行。

**Comment by Likeyong** [comment]
> 把您的GitHub上的的代码拉下来运行的例子，在Android8.1上每次都是弹出"请重试，换个手指试试"。看代码好像defaultDialog中onHelp会执行。

我用了魅族16x android 8.1 测了,没问题, 你要是有时间你新建一个项目,然后gradle 依赖1.0.1 版本再试试

**Comment by AndyFrist** [comment]
依赖了1.0.1版本还是有问题，不知道怎么处理呢。这个问题您是怎么处理的？

**Comment by Likeyong** [comment]
> 依赖了1.0.1版本还是有问题，不知道怎么处理呢。这个问题您是怎么处理的？

我没有遇到你说的问题, 你用的什么设备,  你直接粘贴我MainActivity里面的代码,试试,

**Comment by AndyFrist** [comment]
直接运行您GitHub上的demo就是这个现象呀，项目里也是复制您mainactivity里面的代码，也是这个现象，能加个微信好友吗，13170882739



---原始邮件---
发件人: "Likeyong"<notifications@github.com&gt;
发送时间: 2020年5月12日(周二) 下午5:38
收件人: "Likeyong/FingerManagerCompat"<FingerManagerCompat@noreply.github.com&gt;;
抄送: "AndyFrist"<1609798079@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Likeyong/FingerManagerCompat] 每次都是弹出错误对话框，请重试，换个手指试试 (#3)




  
依赖了1.0.1版本还是有问题，不知道怎么处理呢。这个问题您是怎么处理的？
  
我没有遇到你说的问题, 你用的什么设备,  你直接粘贴我MainActivity里面的代码,试试,

**Comment by Likeyong** [comment]
问题已经修复，请使用最新的1.0.2版本
