### ISSUE TITLE
 updateFingerData() 函数问题

### ISSUE THREAD

**Issue by wangchongwei** [Likeyong/FingerManagerCompat#5]
当调用 updateFingerData()后下一次还是会检测出指纹信息变更，
我看代码在调用是只是更新密钥，但是没有更新is_finger_change 这个值。
不知是否是我使用方法不当，使用的api版本是：**1.0.1**
后面就将这个github项目 clone下来，自己更改了。

**Comment by Likeyong** [comment]
感谢，我在确认一下代码
