### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by 756230883** [Likeyong/FingerManagerCompat#7]
你好 我想请问下 如果走了 onError 这个回调 验证失败了 如何设置才能让他不退出当前界面的情况下 还可以进行再次验证 现在只要 onError 了 就不会再次认证了 麻烦百忙之中给个回复 谢谢

**Comment by Likeyong** [comment]
走到onError  是因为 失败了很多次 比如 识别了三次 或者几次 没识别成功才会走onError,这时候 其实就算一次识别流程结束了。按道理 应该重新开始第二次 而不是接着上一次继续。 你说的 退出当前页面是指 识别的弹窗吗

**Comment by Likeyong** [comment]
> 你好 我想请问下 如果走了 onError 这个回调 验证失败了 如何设置才能让他不退出当前界面的情况下 还可以进行再次验证 现在只要 onError 了 就不会再次认证了 麻烦百忙之中给个回复 谢谢

走到onError 是因为 失败了很多次 比如 识别了三次 或者几次 没识别成功才会走onError,这时候 其实就算一次识别流程结束了。按道理 应该重新开始第二次 而不是接着上一次继续。 你说的 退出当前页面是指 识别的弹窗吗还是指什么

**Comment by 756230883** [comment]
> > 你好 我想请问下 如果走了 onError 这个回调 验证失败了 如何设置才能让他不退出当前界面的情况下 还可以进行再次验证 现在只要 onError 了 就不会再次认证了 麻烦百忙之中给个回复 谢谢
> 
> 走到onError 是因为 失败了很多次 比如 识别了三次 或者几次 没识别成功才会走onError,这时候 其实就算一次识别流程结束了。按道理 应该重新开始第二次 而不是接着上一次继续。 你说的 退出当前页面是指 识别的弹窗吗还是指什么

退出当前页面 是指 退出当前Activity    如果onError了 不退出当前Activity的话  会一直走  onError 只有退出再进 才可以重新识别

**Comment by Likeyong** [comment]
> > > 你好 我想请问下 如果走了 onError 这个回调 验证失败了 如何设置才能让他不退出当前界面的情况下 还可以进行再次验证 现在只要 onError 了 就不会再次认证了 麻烦百忙之中给个回复 谢谢
> > 
> > 
> > 走到onError 是因为 失败了很多次 比如 识别了三次 或者几次 没识别成功才会走onError,这时候 其实就算一次识别流程结束了。按道理 应该重新开始第二次 而不是接着上一次继续。 你说的 退出当前页面是指 识别的弹窗吗还是指什么
> 
> 退出当前页面 是指 退出当前Activity 如果onError了 不退出当前Activity的话 会一直走 onError 只有退出再进 才可以重新识别

运行我的demo 也有这个问题吗
